name: My Locomotive Sites
locales: [en]
domains: [admin.studiowan.fr]
timezone: Paris
seo_title: ''
meta_keywords: ''
meta_description: ''
robots_txt: "User-agent: *\r\nDisallow: /"
metafields:
  info:
    serve: http://my.engine.com/locomotive/api/v3/sites.json
    email: "admin@site.com"
    token: "1234567890"
metafields_ui:
  label: Infos
  icon: gear

